#! /usr/bin/env bash

source "${HOMEgfs}/ush/jjob_header.sh" -e "prep_emissions" -c "base prep_emissions"

##############################################
# Set variables used in the script
##############################################
# TODO: Set local variables used in this script e.g. GDATE may be needed for previous cycle

##############################################
# Begin JOB SPECIFIC work
##############################################
# See config.com for details on the following variables
#   COMIN_CHEM_RESTART_TMPL
#   COM_CHEM_INPUT_TMPL
#   COM_CHEM_HISTORY_TMPL
#   COM_CHEM_RESTART_TMPL
#   COM_CHEM_RESTART_PREV_TMPL
#   COM_ATMOS_HISTORY_TMPL
rCDUMP="${RUN}"
# Ignore possible spelling error (nothing is misspelled)
# shellcheck disable=SC2153
GDATE=$(date --utc -d "${PDY} ${cyc} - ${assim_freq} hours" +%Y%m%d%H)
declare -rx GDATE
# shellcheck disable=
declare -rx gPDY="${GDATE:0:8}"
declare -rx gcyc="${GDATE:8:2}"

RUN="${rCDUMP}" YMD=${gPDY} HH=${gcyc} declare_from_tmpl -rx COMIN_CHEM_RESTART:COM_CHEM_RESTART_TMPL \
    COMIN_ATMOS_HISTORY_PREV:COM_ATMOS_HISTORY_TMPL

YMD=${PDY} HH=${cyc} declare_from_tmpl -rx COMIN_CHEM_INPUT:COM_CHEM_INPUT_TMPL \
    COMOUT_CHEM_HISTORY:COM_CHEM_HISTORY_TMPL \
    COMOUT_CHEM_RESTART:COM_CHEM_RESTART_TMPL

###############################################################
# Run relevant script
EXSCRIPT=${PREP_EMISSIONS_PY:-${SCRgfs}/exglobal_prep_emissions.py}
${EXSCRIPT} && true
export err=$?
if [[ ${err} -ne 0 ]]; then
    err_chk "FATAL ERROR: Error executing ${EXSCRIPT}, ABORT!"
fi

##############################################
# End JOB SPECIFIC work
##############################################

##############################################
# Final processing
##############################################
if [[ -e "${pgmout}" ]] ; then
  cat "${pgmout}"
fi

exit 0
