import os
from typing import Dict, Any
from wxflow import Logger, Jinja, AttrDict, add_to_datetime, to_timedelta, to_YMD, Template, TemplateConstants

logger = Logger(level=os.environ.get("LOGGING_LEVEL", "INFO"))

JJOB_TEMPLATE = """#! /usr/bin/env bash

###############################################################
# EE2 Compliant J-Job generated by JJobGenerator using wxflow
###############################################################

# Standard EE2 environment variables
{% for var in standard_vars -%}
{% if config[var] is defined -%}
export {{ var }}="{{ config[var] }}"
{% endif -%}
{% endfor -%}
export DATA="${DATAROOT}/${jobid}"

# Resolved COM paths (EE2 compliance)
{% for var, val in com_paths.items() -%}
export {{ var }}="{{ val }}"
{% endfor %}
# Execute the Python forecast task
"${HOMEgfs}/scripts/exglobal_forecast.py"
err=$?

if [[ ${err} -ne 0 ]]; then
    echo "Forecast failed with error ${err}"
    exit ${err}
fi

exit 0
"""

class JJobGenerator:
    def __init__(self, config: Dict[str, Any]):
        self.config = AttrDict(config)

    def resolve_template(self, tmpl_str: str, custom_ctx: Dict = None) -> str:
        ctx = self.config.deepcopy()
        if custom_ctx:
            ctx.update(custom_ctx)

        val = tmpl_str
        # Max 10 iterations to avoid infinite loops
        for _ in range(10):
            val = Template.substitute_string(val, TemplateConstants.DOLLAR_CURLY_BRACE, ctx.get)
            if '${' not in val:
                break
        return val

    def generate_gfs_forecast(self) -> str:
        """
        Generate an EE2 compliant JGLOBAL_FORECAST job script
        """
        standard_vars = [
            'envir', 'NET', 'RUN', 'PDY', 'cyc', 'job', 'jobid',
            'DATAROOT', 'COMROOT', 'DCOMROOT', 'HOMEgfs', 'EXPDIR'
        ]

        # Prepare config for template (formatted PDY, cyc)
        tpl_config = self.config.deepcopy()
        if not isinstance(tpl_config.PDY, str):
            tpl_config.PDY = to_YMD(tpl_config.PDY)
        if not isinstance(tpl_config.cyc, str):
            tpl_config.cyc = f"{tpl_config.cyc:02d}"

        com_paths = {}
        mappings = {
            'COMIN_ATMOS_INPUT': 'COM_ATMOS_INPUT_TMPL',
            'COMOUT_CONF': 'COM_CONF_TMPL',
            'COMOUT_ATMOS_RESTART': 'COM_ATMOS_RESTART_TMPL',
            'COMIN_ATMOS_RESTART': 'COM_ATMOS_RESTART_TMPL',
            'COMOUT_ATMOS_HISTORY': 'COM_ATMOS_HISTORY_TMPL',
            'COMOUT_ATMOS_MASTER': 'COM_ATMOS_MASTER_TMPL',
            'COMIN_ATMOS_ANALYSIS': 'COM_ATMOS_ANALYSIS_TMPL'
        }

        ctx = {'YMD': tpl_config.PDY, 'HH': tpl_config.cyc, 'MEMDIR': ''}

        for var, tmpl_key in mappings.items():
            tmpl_str = self.config.get(tmpl_key)
            if tmpl_str:
                com_paths[var] = self.resolve_template(tmpl_str, ctx)

        # Handle Previous Cycle
        current_cycle = add_to_datetime(self.config.PDY, to_timedelta(f"{tpl_config.cyc}H"))
        previous_cycle = add_to_datetime(current_cycle, -to_timedelta(f"{self.config.assim_freq}H"))
        gPDY = to_YMD(previous_cycle)
        gcyc = previous_cycle.strftime("%H")

        rCDUMP = self.config.RUN.replace('gfs', 'gdas').replace('gcafs', 'gcdas')
        prev_ctx = {'RUN': rCDUMP, 'YMD': gPDY, 'HH': gcyc, 'MEMDIR': ''}

        tmpl_str = self.config.get('COM_ATMOS_RESTART_TMPL')
        if tmpl_str:
            com_paths['COMIN_ATMOS_RESTART_PREV'] = self.resolve_template(tmpl_str, prev_ctx)

        data = {
            'config': tpl_config,
            'standard_vars': standard_vars,
            'com_paths': com_paths
        }

        return Jinja(JJOB_TEMPLATE, data).render
